source 'https://rubygems.org'

gem	'sinatra'
gem 'sinatra-contrib'
gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'rack'
gem 'rack-test'
gem 'haml'
gem 'rubocop'
gem 'guard-rubocop'
gem 'imdb', '~> 0.8'
gem 'random-word'
