class Fake_array
  attr_reader :starwars
  def initialize
    @starwars = [[['http://ia.media-imdb.com/images/M/MV5BOTIyMDY2NGQtOGJjNi00OTk4LWFhMDgtYmE3M2NiYzM0YTVmXkEyXkFqcGdeQXVyNTU1NTcwOTk@.jpg'],
                  ['La guerra de las galaxias (1977)']],
                 [['http://ia.media-imdb.com/images/M/MV5BZDgzNzdmNjEtMDAwMC00M2FiLTlkMTEtMDE0MDIyNTEwYmJlXkEyXkFqcGdeQXVyMjY3MjUzNDk@.jpg'],
                  ['Star Wars (1988) (Video Game)']],
                 [[nil], ['Star Wars (1983) (Video Game)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTQ5Nzg4ODczN15BMl5BanBnXkFtZTgwODA1MDY1ODE@.jpg'],
                  ['Rogue One: A Star Wars Story (2016)']],
                 [['http://ia.media-imdb.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@.jpg'],
                  ['Star Wars: El despertar de la fuerza (2015)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMjk1NDk4NjY0Nl5BMl5BanBnXkFtZTgwMzExOTIwODE@.jpg'],
                  ['Star Wars: Episode VIII (2017)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTg4NDg0NTY1OV5BMl5BanBnXkFtZTgwNzY3NDI3NzE@.jpg'],
                  ['Star Wars Rebels (2014) (TV Series)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTM0NjQ2Mjk0OV5BMl5BanBnXkFtZTcwODQ3Njc3Mg@@.jpg'],
                  ['Star Wars: The Clone Wars (2008) (TV Series)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTU2NzYwMzY5OV5BMl5BanBnXkFtZTcwMTQ3MDU3Nw@@.jpg'],
                  ['Star Wars: Wrath of the Mandalorian (2008) (Video)']],
                 [[nil], ['Star Wars: Episode IX (2019)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTI1MDIwMTczOV5BMl5BanBnXkFtZTcwNTI4MDE3MQ@@.jpg'],
                  ['Star Wars: The Clone Wars (2008)']],
                 [['http://ia.media-imdb.com/images/M/MV5BZTdlNzk1OTItZTQxZi00Zjc5LTk2YjAtNDA5N2FlZDEzY2MwXkEyXkFqcGdeQXVyNDM2MzU3Njc@.jpg'],
                  ['Star Wars: Detours (2016) (TV Series)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMGZlMGQxOTAtNzQxZS00OGY0LTkxOTgtZmM5MjgyMTVmMzExXkEyXkFqcGdeQXVyNjU1NzU2ODE@.jpg'],
                  ['Untitled Han Solo Star Wars Anthology Film (2018)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMjE2Mjk5Mzk3M15BMl5BanBnXkFtZTcwMDkzMTIzMQ@@.jpg'],
                  ['Star Wars: Las guerras clon (2003) (TV Series)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTQ4NjEwNDA2Nl5BMl5BanBnXkFtZTcwNDUyNDQzNw@@.jpg'],
                  ['Star Wars: Episodio I - La amenaza fantasma (1999)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTYxNzU0NTc3MF5BMl5BanBnXkFtZTcwNTM1MzEzMQ@@.jpg'],
                  ['Star Wars: Revelations (2005) (Video)']],
                 [['http://ia.media-imdb.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@.jpg'],
                  ['Star Wars: Episodio III - La venganza de los Sith (2005)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTQ0MzI1NjYwOF5BMl5BanBnXkFtZTgwODU3NDU2MTE@.jpg'],
                  ['El retorno del Jedi (1983)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMjE2MzQwMTgxN15BMl5BanBnXkFtZTcwMDQzNjk2OQ@@.jpg'],
                  ['El imperio contraataca (1980)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTY5MjI5NTIwNl5BMl5BanBnXkFtZTYwMTM1Njg2.jpg'],
                  ['Star Wars: Episodio II - El ataque de los clones (2002)']],
                 [[nil], ['Star Wars City (1985) (TV Movie)']],
                 [[nil], ['Star Wars: Underworld (TV Series)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTk5NzE4MWMtZTZkOS00NzE2LTk2NTItYjlkNjI3ZDcyYTdlXkEyXkFqcGdeQXVyMzM4MjM0Nzg@.jpg'],
                  ['Star Wars (1991) (Video Game)']],
                 [[nil], ['SDI Star Wars (1991) (Video)']],
                 [['http://ia.media-imdb.com/images/M/MV5BMTI2MTUwMjczM15BMl5BanBnXkFtZTcwNDA0NjA4MQ@@.jpg'],
                  ['Star Wars: The Force Unleashed (2008) (Video Game)']],
                 [['http://ia.media-imdb.com/images/M/MV5BODEzODczNjQ1Ml5BMl5BanBnXkFtZTgwOTY1MDUxNzE@.jpg'],
                  ['Star Wars: Battlefront (2015) (Video Game)']]]
  end
end
